### ISSUE TITLE
Error "Fatal Python error: failed to get random numbers to initialize Python" when trying to launch docker container

### ISSUE THREAD

**Issue by Rexhaif** [IINemo/isanlp#6]
Hello,
Recently i've pulled latest docker image of isanlp and runned it using command:
`docker run -ti --rm -p 3333:3333 --name isanlp-0 inemo/isanlp`
But, shortly after, i've got an error:
> Fatal Python error: failed to get random numbers to initialize Python
> /entrypoint.sh: line 3:     7 Aborted                 (core dumped) $@

System info:
`uname -a`
> Linux exn40 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux

`docker --version`
> Docker version 17.03.0-ce, build 60ccb22

**Comment by IINemo** [comment]
Use newer kernel version.
